[package]
name = "redis"
version = "0.1.0"
authors = ["Federico Ravasio <ravasio.federico@gmail.com>"]

[dependencies]

[lib]
name = "redis"
path = "src/redis/lib.rs"
bench = false
doctest = false

[[bin]]
name = "redis"
bench = false
doc = false
test = false
