[package]
name = "redis"
version = "0.1.0"
authors = ["Federico Ravasio <ravasio.federico@gmail.com>"]

[dependencies]
nom = "1.2.3"

[dev-dependencies]
quickcheck = "0.2.27"
quickcheck_macros = "0.2.26"
